---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: veraeasy-app
  namespace: veraeasy-full
spec:
  replicas: 1
  selector:
    matchLabels:
      app: veraeasy-app
  template:
    metadata:
      labels:
        app: veraeasy-app
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
        - name: veraeasy-app
          image: veraeasy.azurecr.io/veraeasy-app:latest
          imagePullPolicy: Always
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: 'yes'
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          ports:
            - containerPort: 80
              name: http
      hostAliases:
        - ip: "10.0.226.123"
          hostnames:
            - "veraeasy-backend"
        - ip: "10.0.93.16"
          hostnames:
            - "veraeasy-verifier-backend"
            - "veraeasy-backend-verifier"
---
apiVersion: v1
kind: Service
metadata:
  name: veraeasy-app
  namespace: veraeasy-full
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: veraeasy-app